#!/usr/bin/env python

import os
from munin import MuninPlugin
import mysql.connector


conn = mysql.connector.Connect(host='localhost',user='root',\
                        password='smx',database='meteopy')


class LoadAVGPlugin(MuninPlugin):
    title = "Pressio Atmosferica"
    args = ""
    args = "--base 1000"
    vlabel = "pressio"
    category = "meteopy"

    @property

    def fields(self):
        warning = os.environ.get('load_warn', 10)
        critical = os.environ.get('load_crit', 2000)
        return [("pressio", dict(
                label = "pressio",
                info = 'Pressio recollida per el sensor.',
                type = "GAUGE",
                graph_scale = "no",
                min = "0",
                warning = str(warning),
                critical = str(critical)))]

    def execute(self):
        c = conn.cursor()

	conn.commit()

	c.execute ("""SELECT press FROM `press` WHERE ID= 1""")

	for row in c:
        	resultat=(row)
	final=str(resultat)[1:-2]


        return dict(pressio=final)

if __name__ == "__main__":
    LoadAVGPlugin().run()
